controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

program_show:
    path: /program/{id}/
    controller: App\Controller\ProgramController::show
    methods: GET
    requirements:
        id: \d+  # Assurez-vous que l'id est un entier